sudo: false

language: ruby

cache: bundler

rvm:
  - 2.2.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - "cp config/database.travis.yml config/database.yml"
  - "RAILS_ENV=test bundle exec rake db:create"

